# Generated by Django 5.2.7 on 2025-11-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlcontent',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to='html/'),
        ),
    ]
