# Generated by Django 5.2.7 on 2025-10-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIintergration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfhistory',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
