/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MyContentsRouteImport } from './routes/my-contents'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateContentRouteImport } from './routes/create-content'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentContentIdRouteImport } from './routes/content/$contentId'
import { Route as ContentContentIdEditRouteImport } from './routes/content/$contentId/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MyContentsRoute = MyContentsRouteImport.update({
  id: '/my-contents',
  path: '/my-contents',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateContentRoute = CreateContentRouteImport.update({
  id: '/create-content',
  path: '/create-content',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentContentIdRoute = ContentContentIdRouteImport.update({
  id: '/content/$contentId',
  path: '/content/$contentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentContentIdEditRoute = ContentContentIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ContentContentIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-content': typeof CreateContentRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-contents': typeof MyContentsRoute
  '/signup': typeof SignupRoute
  '/content/$contentId': typeof ContentContentIdRouteWithChildren
  '/content/$contentId/edit': typeof ContentContentIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-content': typeof CreateContentRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-contents': typeof MyContentsRoute
  '/signup': typeof SignupRoute
  '/content/$contentId': typeof ContentContentIdRouteWithChildren
  '/content/$contentId/edit': typeof ContentContentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_public': typeof PublicRoute
  '/create-content': typeof CreateContentRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-contents': typeof MyContentsRoute
  '/signup': typeof SignupRoute
  '/content/$contentId': typeof ContentContentIdRouteWithChildren
  '/content/$contentId/edit': typeof ContentContentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-content'
    | '/dashboard'
    | '/login'
    | '/my-contents'
    | '/signup'
    | '/content/$contentId'
    | '/content/$contentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-content'
    | '/dashboard'
    | '/login'
    | '/my-contents'
    | '/signup'
    | '/content/$contentId'
    | '/content/$contentId/edit'
  id:
    | '__root__'
    | '/'
    | '/_public'
    | '/create-content'
    | '/dashboard'
    | '/login'
    | '/my-contents'
    | '/signup'
    | '/content/$contentId'
    | '/content/$contentId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicRoute: typeof PublicRoute
  CreateContentRoute: typeof CreateContentRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MyContentsRoute: typeof MyContentsRoute
  SignupRoute: typeof SignupRoute
  ContentContentIdRoute: typeof ContentContentIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-contents': {
      id: '/my-contents'
      path: '/my-contents'
      fullPath: '/my-contents'
      preLoaderRoute: typeof MyContentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-content': {
      id: '/create-content'
      path: '/create-content'
      fullPath: '/create-content'
      preLoaderRoute: typeof CreateContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$contentId': {
      id: '/content/$contentId'
      path: '/content/$contentId'
      fullPath: '/content/$contentId'
      preLoaderRoute: typeof ContentContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$contentId/edit': {
      id: '/content/$contentId/edit'
      path: '/edit'
      fullPath: '/content/$contentId/edit'
      preLoaderRoute: typeof ContentContentIdEditRouteImport
      parentRoute: typeof ContentContentIdRoute
    }
  }
}

interface ContentContentIdRouteChildren {
  ContentContentIdEditRoute: typeof ContentContentIdEditRoute
}

const ContentContentIdRouteChildren: ContentContentIdRouteChildren = {
  ContentContentIdEditRoute: ContentContentIdEditRoute,
}

const ContentContentIdRouteWithChildren =
  ContentContentIdRoute._addFileChildren(ContentContentIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicRoute: PublicRoute,
  CreateContentRoute: CreateContentRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MyContentsRoute: MyContentsRoute,
  SignupRoute: SignupRoute,
  ContentContentIdRoute: ContentContentIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
