# Generated by Django 4.2.25 on 2025-11-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='html_file',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
